### ISSUE TITLE
有没有MicroTask和MacroTask的一些介绍呢

### ISSUE THREAD

**Issue by hyj1991** [yjhjstz/deep-into-node#11]
目前只看到Promise的Then方法注册的回调函数是在MicroTask队列中被依次执行的，还有别的方法是在MicroTask队列中执行的么？还有就是我搜遍源代码也没看到MacroTask队列的东西，请问这个到底是什么，用来执行哪些内容的呢？

**Comment by hyj1991** [comment]
这个似乎算是V8引擎的部分了，不是Node的东西了，如果不方便回答的话我就关闭吧，感谢作者的分享，对我们这种菜鸟阅读源代码少走了很多弯路~

**Comment by yjhjstz** [comment]
MicroTask确实在 v8 层实现，我先上一张图，你先看看。
![cy-m8dmuqaallep jpg-large](https://cloud.githubusercontent.com/assets/3832082/22230884/2d52c2b4-e21b-11e6-9c8b-5593da619bd3.jpeg)

**Comment by hyj1991** [comment]
看了下这个图，有几个疑问：
1.我目前看的源码是v6.9.1的，这里的```process.nextTick```的回调处理函数(nextTickQueue队列)是直接调用：
```
env->set_tick_callback_function(args[0].As<Function>());
```
的方式注册到Env的，然后在每一个异步回调中的```AsyncWrap::MakeCallback```中等待异步回调函数执行完成后，使用：
```
env()->tick_callback_function()->Call(process, 0, nullptr)
```
的方式被执行的，这样子看的话，Node实现的Promise.nextTick虽然确实也没走Event Loop，但是似乎也不算是在Microtask Queue中被执行的吧，可以这样认为么？（Promise.js的then方法实现确实看到了%EnqueueMicrotask这样的方式注册）

**Comment by yjhjstz** [comment]
1. `process.nextTick` 和 `Promise` 都用到了 v8 的 `Microtask Queue`；
2. `Task Queue`对于 `setImmediate` 来说就是： `immediateQueue`,  javascript 层面实现是链表；
3. Stack 是函数栈。BackGround 线程池运行同步调用比如 `read`。

**Comment by hyj1991** [comment]
结合图和您最后的解惑回答，感觉理解的更深了，非常感谢！
