### ISSUE TITLE
这里的引用是C++中引用的概念吗？

### ISSUE THREAD

**Issue by Kpyu** [yjhjstz/deep-into-node#14]
如题，或者是js语言中引用的概念？

**Comment by yjhjstz** [comment]
这里是文章的哪里呢？

**Comment by Kpyu** [comment]
Handle 概念

在 V8 中，内存分配都是在 V8 的 Heap 中进行分配的，JavaScript 的值和对象也都存放在 V8 的 Heap 中。这个 Heap 由 V8 独立的去维护，失去引 用的对象将会被 V8 的 GC 掉并可以重新分配给其他对象。而 Handle 即是对 Heap 中对象的`引用`。

**Comment by yjhjstz** [comment]
Handle 实现其实是指针的指针。
