### ISSUE TITLE
generator

### ISSUE THREAD

**Issue by lezi1022** [yjhjstz/deep-into-node#2]
deep-into-node，不能缺少generator相关的东西吧，作为从c转到nodejs的开发者，很好奇js的yield是底层怎么实现的

**Comment by yjhjstz** [comment]
恩，不错的提议，yield 底层实现是在 v8 层面，后面我研究下，写一或多篇文章来介绍下。
也欢迎提更多的意见。

**Comment by yjhjstz** [comment]
https://yjhjstz.gitbooks.io/deep-into-node/content/chapter3/chapter3-2.html
汇编部分比较晦涩，没有展开写。

**Comment by sodawy** [comment]
赞行动力

**Comment by joyeecheung** [comment]
Note: generator 在去年重新实现了一遍，现在走 ignition + turbofan
