### ISSUE TITLE
__filename && __dirname not global 

### ISSUE THREAD

**Issue by hanhuizhu** [yjhjstz/deep-into-node#23]
![image](https://user-images.githubusercontent.com/20557589/50128665-defaf880-02b0-11e9-8902-7913dc8b097c.png)

**Comment by yjhjstz** [comment]
请指教？

**Comment by hanhuizhu** [comment]
filename 和 dirname 不是file 闭包时传入的两个参数？没有挂载在global 对象下

**Comment by yjhjstz** [comment]
方便提交一个fix吗？

**Comment by hanhuizhu** [comment]
好了

**Comment by yjhjstz** [comment]
#24
