### ISSUE TITLE
chapter2/chapter2-0 中引用的图片挂掉了

### ISSUE THREAD

**Issue by yushen7** [yjhjstz/deep-into-node#37]
> https://github.com/yjhjstz/deep-into-node/blob/master/chapter2/chapter2-0.md

如下图「堆的组成」这一小节：

![(V4Y7M9GVXL}{8Y9KJ{@8%R](https://user-images.githubusercontent.com/35678187/89290727-e04a8600-d68b-11ea-8dc8-59904d0bb50a.png)

**Comment by yjhjstz** [comment]
https://github.com/yjhjstz/deep-into-node/blob/master/chapter2/chapter2-0.md 打开全局代理后图可以显示。

**Comment by yushen7** [comment]
> https://github.com/yjhjstz/deep-into-node/blob/master/chapter2/chapter2-0.md 打开全局代理后图可以显示。

抱歉~不是很懂，但「原始的」错误看起来是这样的：
![JHCEXCOXJTZ@DK)DX)($1HK](https://user-images.githubusercontent.com/35678187/89292975-c1e68980-d68f-11ea-9425-6ece3b15a701.png)

**Comment by yjhjstz** [comment]
嗯，是githubusercontent.com 的访问问题。
