### ISSUE TITLE
nodejs 和浏览器事件循环实现有什么区别？

### ISSUE THREAD

**Issue by wmzy** [yjhjstz/deep-into-node#9]
nodejs 和浏览器（比如chrome）在事件循环的实现有没有什么不同？能详细讲一下么？

**Comment by yjhjstz** [comment]
先看图 chrome：
![3259161542-575018ce29d44_articlex](https://cloud.githubusercontent.com/assets/3832082/20128427/d93cdb8e-a682-11e6-8844-962121f9fae0.png)

nodejs 和 chrome 的事件驱动实现上：

node.js 事件由 libuv 驱动，chrome 由 webkit 实现。

**Comment by rawbin-** [comment]
nodejs 使用v8 作为JavaScript解析，同样的chrome 内核 webkit 也是用v8作为JavaScript解析
nodejs 使用libuv，chrome 难道不是么？

**Comment by hyj1991** [comment]
@rawbin- 浏览器不用 libuv

**Comment by rawbin-** [comment]
那在哪里可以看得到，浏览器用的什么库或者怎么实现的呢？

**Comment by yjhjstz** [comment]
clone webkit 看看
